const responseToDBJson = function(schoolListData) {
    return schoolListData.map(schoolData => {
        return {
            college_id: schoolData.id,
            school_name: schoolData.school.name,
            school_url: schoolData.school.school_url,
            school_alias: schoolData.school.alias,
            religious_affiliation: schoolData.school.religious_affiliation ? 1 : 0,
            public_school: Object.values(schoolData.latest.cost.net_price.public.by_income_level).filter(val => val != null).length ? 1 : 0,
            normal_graduation_rate: schoolData.latest.completion.rate_suppressed.overall,
            state: schoolData.school.state,
            city: schoolData.school.city,
            longitude: schoolData.location.lon,
            latitude: schoolData.location.lat,
            institutional_level: schoolData.school.institutional_characteristics.level,
            men_only: schoolData.school.men_only,
            women_only: schoolData.school.women_only,
            hispanic_school: schoolData.school.minority_serving.hispanic,
            tribal_school: schoolData.school.minority_serving.tribal,
            historically_black_school: schoolData.school.minority_serving.historically_black,
            predominantly_black_school: schoolData.school.minority_serving.predominantly_black,
            alaskan_native_and_native_hawaiian_school: schoolData.school.minority_serving.annh,
            asian_american_native_american_and_pacific_islander_school: schoolData.school.minority_serving.aanipi,
            native_american_non_tribal_school: schoolData.school.minority_serving.nant,
            title_iv_eligible: schoolData.school.title_iv.eligibility_type,
            overall_average_sat: schoolData.latest.admissions.sat_scores.average.overall,
            sat_25_percentile_critical_reading: schoolData.latest.admissions.sat_scores['25th_percentile'].critical_reading,
            sat_25_percentile_math: schoolData.latest.admissions.sat_scores['25th_percentile'].math,
            sat_25_percentile_writing: schoolData.latest.admissions.sat_scores['25th_percentile'].writing,
            sat_50_percentile_critical_reading: schoolData.latest.admissions.sat_scores.midpoint.critical_reading,
            sat_50_percentile_math: schoolData.latest.admissions.sat_scores.midpoint.math,
            sat_50_percentile_writing: schoolData.latest.admissions.sat_scores.midpoint.writing,
            sat_75_percentile_critical_reading: schoolData.latest.admissions.sat_scores['75th_percentile'].critical_reading,
            sat_75_percentile_math: schoolData.latest.admissions.sat_scores['75th_percentile'].math,
            sat_75_percentile_writing: schoolData.latest.admissions.sat_scores['75th_percentile'].writing,
            act_25_percentile_cumulative: schoolData.latest.admissions.act_scores['25th_percentile'].cumulative,
            act_25_percentile_english: schoolData.latest.admissions.act_scores['25th_percentile'].english,
            act_25_percentile_math: schoolData.latest.admissions.act_scores['25th_percentile'].math,
            act_25_percentile_writing: schoolData.latest.admissions.act_scores['25th_percentile'].writing,
            act_50_percentile_cumulative: schoolData.latest.admissions.act_scores.midpoint.cumulative,
            act_50_percentile_english: schoolData.latest.admissions.act_scores.midpoint.english,
            act_50_percentile_math: schoolData.latest.admissions.act_scores.midpoint.math,
            act_50_percentile_writing: schoolData.latest.admissions.act_scores.midpoint.writing,
            act_75_percentile_cumulative: schoolData.latest.admissions.act_scores['75th_percentile'].cumulative,
            act_75_percentile_english: schoolData.latest.admissions.act_scores['75th_percentile'].english,
            act_75_percentile_math: schoolData.latest.admissions.act_scores['75th_percentile'].math,
            act_75_percentile_writing: schoolData.latest.admissions.act_scores['75th_percentile'].writing,
            admission_rate: schoolData.latest.admissions.admission_rate.overall || 0,
            grad_students_enrolled: schoolData.latest.student.grad_students || 0,
            undergrad_students_enrolled: schoolData.latest.student.size || 0,
            total_enrollment: (schoolData.latest.student.grad_students || 0) + (schoolData.latest.student.size || 0),
            income_0_30000_percentage: (schoolData.latest.student.share_lowincome['0_30000'] || 0) * 100,
            income_30001_48000_percentage: (schoolData.latest.student.share_lowincome['30001_48000'] || 0) * 100,
            income_48001_75000_percentage: (schoolData.latest.student.share_lowincome['48001_75000'] || 0) * 100,
            income_75001_110000_percentage: (schoolData.latest.student.share_lowincome['75001_110000'] || 0) * 100,
            income_110001_plus_percentage: (schoolData.latest.student.share_lowincome['110001plus'] || 0) * 100,
            average_family_income: schoolData.latest.student.demographics.avg_family_income,
            men_percentage: schoolData.latest.student.demographics.men || 0,
            women_percentage: schoolData.latest.student.demographics.women || 0,
            native_american_or_alaskan_native_student_percentage: schoolData.latest.student.demographics.race_ethnicity.aian || 0,
            asian_student_percentage: schoolData.latest.student.demographics.race_ethnicity.asian || 0,
            asian_pacific_islander_student_percentage: schoolData.latest.student.demographics.race_ethnicity.asian_pacific_islander || 0,
            black_student_percentage: schoolData.latest.student.demographics.race_ethnicity.black || 0,
            hispanic_student_percentage: schoolData.latest.student.demographics.race_ethnicity.hispanic || 0,
            white_student_percentage: schoolData.latest.student.demographics.race_ethnicity.white || 0,
            native_hawaiian_pacific_islander_student_population: schoolData.latest.student.demographics.race_ethnicity.nhpi || 0,
            non_resident_immigrant_student_population: schoolData.latest.student.demographics.race_ethnicity.non_resident_alien || 0,
            multiple_race_student_population: schoolData.latest.student.demographics.race_ethnicity.two_or_more || 0,
            unknown_race_student_population: schoolData.latest.student.demographics.race_ethnicity.unkown || 0,
            in_state_tuition: schoolData.latest.cost.tuition.in_state,
            out_of_state_tuition: schoolData.latest.cost.tuition.out_of_state,
            average_income_post_graduation: schoolData.latest.earnings['8_yrs_after_entry'].mean_earnings,
            business_marketing_offered: schoolData.latest.academics.program.degree.business_marketing,
            family_consumer_science_offered: schoolData.latest.academics.program.degree.family_consumer_science,
            humanities_offered: schoolData.latest.academics.program.degree.humanities,
            communications_technology_offered: schoolData.latest.academics.program.degree.communications_technology,
            mathematics_offered: schoolData.latest.academics.program.degree.mathematics,
            language_offered: schoolData.latest.academics.program.degree.language,
            engineering_technology_offered: schoolData.latest.academics.program.degree.engineering_technology,
            english_offered: schoolData.latest.academics.program.degree.english,
            transportation_offered: schoolData.latest.academics.program.degree.transportation,
            personal_culinary_offered: schoolData.latest.academics.program.degree.personal_culinary,
            physical_science_offered: schoolData.latest.academics.program.degree.physical_science,
            psychology_offered: schoolData.latest.academics.program.degree.psychology,
            engineering_offered: schoolData.latest.academics.program.degree.engineering,
            mechanic_repair_technology_offered: schoolData.latest.academics.program.degree.mechanic_repair_technology,
            resources_offered: schoolData.latest.academics.program.degree.resources,
            computer_offered: schoolData.latest.academics.program.degree.computer,
            communication_offered: schoolData.latest.academics.program.degree.communication,
            security_law_enforcemen_offeredt: schoolData.latest.academics.program.degree.security_law_enforcement,
            precision_production_offered: schoolData.latest.academics.program.degree.precision_production,
            legal_offered: schoolData.latest.academics.program.degree.legal,
            agriculture_offered: schoolData.latest.academics.program.degree.agriculture,
            biological_offered: schoolData.latest.academics.program.degree.biological,
            philosophy_religious_offered: schoolData.latest.academics.program.degree.philosophy_religious,
            architecture_offered: schoolData.latest.academics.program.degree.architecture,
            theology_religious_vocation_offered: schoolData.latest.academics.program.degree.theology_religious_vocation,
            education_offered: schoolData.latest.academics.program.degree.education,
            construction_offered: schoolData.latest.academics.program.degree.construction,
            history_offered: schoolData.latest.academics.program.degree.history,
            visual_performing_offered: schoolData.latest.academics.program.degree.visual_performing,
            social_science_offered: schoolData.latest.academics.program.degree.social_science,
            library_offered: schoolData.latest.academics.program.degree.library,
            health_offered: schoolData.latest.academics.program.degree.health,
            science_technology_offered: schoolData.latest.academics.program.degree.science_technology,
            public_administration_social_service_offered: schoolData.latest.academics.program.degree.public_administration_social_service,
            parks_recreation_fitness_offered: schoolData.latest.academics.program.degree.parks_recreation_fitness,
            ethnic_cultural_gender_offered: schoolData.latest.academics.program.degree.ethnic_cultural_gender,
            military_offered: schoolData.latest.academics.program.degree.military,
            multidiscipline_offered: schoolData.latest.academics.program.degree.multidiscipline,
            business_marketing_percentage: schoolData.latest.academics.program_percentage.business_marketing,
            family_consumer_science_percentage: schoolData.latest.academics.program_percentage.family_consumer_science,
            humanities_percentage: schoolData.latest.academics.program_percentage.humanities,
            communications_technology_percentage: schoolData.latest.academics.program_percentage.communications_technology,
            mathematics_percentage: schoolData.latest.academics.program_percentage.mathematics,
            language_percentage: schoolData.latest.academics.program_percentage.language,
            engineering_technology_percentage: schoolData.latest.academics.program_percentage.engineering_technology,
            english_percentage: schoolData.latest.academics.program_percentage.english,
            transportation_percentage: schoolData.latest.academics.program_percentage.transportation,
            personal_culinary_percentage: schoolData.latest.academics.program_percentage.personal_culinary,
            physical_science_percentage: schoolData.latest.academics.program_percentage.physical_science,
            psychology_percentage: schoolData.latest.academics.program_percentage.psychology,
            engineering_percentage: schoolData.latest.academics.program_percentage.engineering,
            mechanic_repair_technology_percentage: schoolData.latest.academics.program_percentage.mechanic_repair_technology,
            resources_percentage: schoolData.latest.academics.program_percentage.resources,
            computer_percentage: schoolData.latest.academics.program_percentage.computer,
            communication_percentage: schoolData.latest.academics.program_percentage.communication,
            security_law_enforcemen_percentaget: schoolData.latest.academics.program_percentage.security_law_enforcement,
            precision_production_percentage: schoolData.latest.academics.program_percentage.precision_production,
            legal_percentage: schoolData.latest.academics.program_percentage.legal,
            agriculture_percentage: schoolData.latest.academics.program_percentage.agriculture,
            biological_percentage: schoolData.latest.academics.program_percentage.biological,
            philosophy_religious_percentage: schoolData.latest.academics.program_percentage.philosophy_religious,
            architecture_percentage: schoolData.latest.academics.program_percentage.architecture,
            theology_religious_vocation_percentage: schoolData.latest.academics.program_percentage.theology_religious_vocation,
            education_percentage: schoolData.latest.academics.program_percentage.education,
            construction_percentage: schoolData.latest.academics.program_percentage.construction,
            history_percentage: schoolData.latest.academics.program_percentage.history,
            visual_performing_percentage: schoolData.latest.academics.program_percentage.visual_performing,
            social_science_percentage: schoolData.latest.academics.program_percentage.social_science,
            library_percentage: schoolData.latest.academics.program_percentage.library,
            health_percentage: schoolData.latest.academics.program_percentage.health,
            science_technology_percentage: schoolData.latest.academics.program_percentage.science_technology,
            public_administration_social_service_percentage: schoolData.latest.academics.program_percentage.public_administration_social_service,
            parks_recreation_fitness_percentage: schoolData.latest.academics.program_percentage.parks_recreation_fitness,
            ethnic_cultural_gender_percentage: schoolData.latest.academics.program_percentage.ethnic_cultural_gender,
            military_percentage: schoolData.latest.academics.program_percentage.military,
            multidiscipline_percentage: schoolData.latest.academics.program_percentage.multidiscipline
        }
    });
}

module.exports = {
    responseToDBJson
}