const responseToDBJson = function(schoolListData) {
    return schoolListData.map(schoolData => {
        return {
            id: schoolData.id,
            school_name: schoolData.school.name,
            school_url: schoolData.school.school_url,
            state: schoolData.school.state,
            city: schoolData.school.city,
            longitude: schoolData.location.lon,
            latitude: schoolData.location.lat,
            institutional_level: schoolData.school.institutional_characteristics.level,
            men_only: schoolData.school.men_only,
            women_only: schoolData.school.women_only,
            hispanic_school: schoolData.school.minority_serving.hispanic,
            tribal_school: schoolData.school.minority_serving.tribal,
            historically_black_school: schoolData.school.minority_serving.historically_black,
            predominantly_black_school: schoolData.school.minority_serving.predominantly_black,
            alaskan_native_and_native_hawaiian_school: schoolData.school.minority_serving.annh,
            asian_american_native_american_and_pacific_islander_school: schoolData.school.minority_serving.aanipi,
            native_american_non_tribal_school: schoolData.school.minority_serving.nant,
            title_iv_eligible: schoolData.school.title_iv.eligibility_type,
            overall_average_sat: schoolData.latest.admissions.sat_scores.average.overall,
            sat_25_percentile_critical_reading: schoolData.latest.admissions.sat_scores['25th_percentile'].critical_reading,
            sat_25_percentile_math: schoolData.latest.admissions.sat_scores['25th_percentile'].math,
            sat_25_percentile_writing: schoolData.latest.admissions.sat_scores['25th_percentile'].writing,
            sat_50_percentile_critical_reading: schoolData.latest.admissions.sat_scores.midpoint.critical_reading,
            sat_50_percentile_math: schoolData.latest.admissions.sat_scores.midpoint.math,
            sat_50_percentile_writing: schoolData.latest.admissions.sat_scores.midpoint.writing,
            sat_75_percentile_critical_reading: schoolData.latest.admissions.sat_scores['75th_percentile'].critical_reading,
            sat_75_percentile_math: schoolData.latest.admissions.sat_scores['75th_percentile'].math,
            sat_75_percentile_writing: schoolData.latest.admissions.sat_scores['75th_percentile'].writing,
            act_25_percentile_cumulative: schoolData.latest.admissions.act_scores['25th_percentile'].cumulative,
            act_25_percentile_english: schoolData.latest.admissions.act_scores['25th_percentile'].english,
            act_25_percentile_math: schoolData.latest.admissions.act_scores['25th_percentile'].math,
            act_25_percentile_writing: schoolData.latest.admissions.act_scores['25th_percentile'].writing,
            act_50_percentile_cumulative: schoolData.latest.admissions.act_scores.midpoint.cumulative,
            act_50_percentile_english: schoolData.latest.admissions.act_scores.midpoint.english,
            act_50_percentile_math: schoolData.latest.admissions.act_scores.midpoint.math,
            act_50_percentile_writing: schoolData.latest.admissions.act_scores.midpoint.writing,
            act_75_percentile_cumulative: schoolData.latest.admissions.act_scores['75th_percentile'].cumulative,
            act_75_percentile_english: schoolData.latest.admissions.act_scores['75th_percentile'].english,
            act_75_percentile_math: schoolData.latest.admissions.act_scores['75th_percentile'].math,
            act_75_percentile_writing: schoolData.latest.admissions.act_scores['75th_percentile'].writing,
            admission_rate: schoolData.latest.admissions.admission_rate.overall || 0,
            grad_students_enrolled: schoolData.latest.student.grad_students || 0,
            undergrad_students_enrolled: schoolData.latest.student.size || 0,
            total_enrollment: (schoolData.latest.student.grad_students || 0) + (schoolData.latest.student.size || 0),
            income_0_30000_percentage: (schoolData.latest.student.share_lowincome['0_30000'] || 0) * 100,
            income_30001_48000_percentage: (schoolData.latest.student.share_lowincome['30001_48000'] || 0) * 100,
            income_48001_75000_percentage: (schoolData.latest.student.share_lowincome['48001_75000'] || 0) * 100,
            income_75001_110000_percentage: (schoolData.latest.student.share_lowincome['75001_110000'] || 0) * 100,
            income_110001_plus_percentage: (schoolData.latest.student.share_lowincome['110001plus'] || 0) * 100,
            average_family_income: schoolData.latest.student.demographics.avg_family_income,
            median_family_income: schoolData.latest.student.demographics.median_family_income,
            median_household_income: schoolData.latest.student.demographics.median_hh_income,
            men_percentage: schoolData.latest.student.demographics.men || 0,
            women_percentage: schoolData.latest.student.demographics.women || 0,
            native_american_or_alaskan_native_student_percentage: schoolData.latest.student.demographics.race_ethnicity.aian || 0,
            asian_student_percentage: schoolData.latest.student.demographics.race_ethnicity.asian || 0,
            asian_pacific_islander_student_percentage: schoolData.latest.student.demographics.race_ethnicity.asian_pacific_islander || 0,
            black_student_percentage: schoolData.latest.student.demographics.race_ethnicity.black || 0,
            hispanic_student_percentage: schoolData.latest.student.demographics.race_ethnicity.hispanic || 0,
            white_student_percentage: schoolData.latest.student.demographics.race_ethnicity.white || 0,
            native_hawaiian_pacific_islander_student_population: schoolData.latest.student.demographics.race_ethnicity.nhpi || 0,
            non_resident_immigrant_student_population: schoolData.latest.student.demographics.race_ethnicity.non_resident_alien || 0,
            multiple_race_student_population: schoolData.latest.student.demographics.race_ethnicity.two_or_more || 0,
            unknown_race_student_population: schoolData.latest.student.demographics.race_ethnicity.unkown || 0,
            in_state_tuition: schoolData.latest.cost.tuition.in_state,
            out_of_state_tuition: schoolData.latest.cost.tuition.out_of_state
        }
    });
}

module.exports = {
    responseToDBJson
}